#!/bin/sh

if [ $# -ne 2 ];then
	echo "Usage: $0 input.mgz output.mnc"
	exit
fi

export FREESURFER_HOME=/Applications/freesurfer

if [ -f $1 ]; then
    cras=`$FREESURFER_HOME/bin/mri_info --cras $1`
else
    echo File $1 not found
    exit
fi

# extract xyz center
x=`echo $cras|cut -f1 -d' '`
y=`echo $cras|cut -f2 -d' '`
z=`echo $cras|cut -f3 -d' '`

# invert values
x=`echo -$x |sed -e 's/--//g'`
y=`echo -$y |sed -e 's/--//g'`
z=`echo -$z |sed -e 's/--//g'`

# create xfm file with shifting
echo "MNI Transform File\n\nTransform_Type=Linear;\nLinear_Transform = \n1 0 0 $x\n0 1 0 $y\n0 0 1 $z;\n" >> /tmp/$$.xfm

$FREESURFER_HOME/bin/mri_convert -oid 1 0 0 -ojd 0 1 0 -okd 0 0 1 --apply_transform /tmp/$$.xfm $1 $2

rm /tmp/$$.xfm
